= Lab prerequisites
include::_attributes.adoc[]


== TL/DR

* Virtualization hypervisor (lab steps are based on libvirt): 
** Red Hat Enterprise Linux 8/9 VM minimal-install subscribed (2 vCPUs, 4 GB memory, 50 GB disk)
** Empty VM with UEFI boot enabled (2 vCPUs, 1.5 GB memory, 20GB disk)
* Internet connection from VMs
* (optional) Red Hat Enterprise Linux 8/9 boot ISO



[#virtualization]
== Prepare your virtualization environment

Although you can use the steps shown in this tutorial to onboard RHEL on baremetal devices, for simplicity, we will be using virtual machines for this lab, so you will need to have a pre-configured hypervisor (which could be libvirt running on your laptop if you have enough resources) where we will be running the required servers and also to create the edge devices.

Depending on the use case or configuration that you want to follow during this lab, you could need to add "special" devices to your edge VM, for example, you probably would like to use a virtual TPM to manage keys as you will be doing it with physical devices on real edge environments.

This lab could be run completly offline, but in order to avoid creating local repositories we will be connecting to the public ones, so you will need Internet access from your VMs.

[#arch]
== Choose your lab architecture

The lab environment will be composed by an edge device and one or multiple servers. You can deploy all servers in a single VM if you are short in CPU/MEM resources in your hypervisor (laptop?) or you can split services in dedicated VMs to try a more "realistic" architecture.

=== Option 1: All-in-one server


=== Option 2: Dedicated server VMs






CPU and  mem



ISO download 


registered sub




[#usecase]
== Create your use case












